# Checkov Configuration
# Documentation: https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html

skip-path:
  - Future/
  - .terraform/
  - terraform/test-security-issues.tf

skip-check:
  - CKV_K8S_35  # Secrets as env vars acceptable for Jobs with proper RBAC
  - CKV_K8S_43  # Public registry images acceptable in our context
  - CKV_OCI_5   # Legacy metadata service - needed for instance configuration
  - CKV_OCI_17  # Stateless security lists - stateful required for our use case
  - CKV_OCI_19  # SSH from 0.0.0.0/0 - Required for control plane access
  - CKV_OCI_20  # RDP from 0.0.0.0/0 - Dev/test environment acceptable risk
