apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: image-verification
  annotations:
    policies.kyverno.io/title: Image Verification
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Enforce image verification and approved registries.
spec:
  validationFailureAction: enforce
  background: true
  rules:
    # Disallow latest tag
    - name: disallow-latest-tag
      match:
        any:
        - resources:
            kinds:
              - Deployment
              - StatefulSet
              - DaemonSet
      validate:
        message: "Using 'latest' tag is not allowed. Use specific version tags."
        pattern:
          spec:
            template:
              spec:
                containers:
                - image: "!*:latest"
    
    # Require images from approved registries
    - name: require-approved-registry
      match:
        any:
        - resources:
            kinds:
              - Deployment
              - StatefulSet
              - DaemonSet
            namespaces:
              - production
      validate:
        message: "Images must be from approved registries (docker.io, ghcr.io, gcr.io)"
        anyPattern:
        - spec:
            template:
              spec:
                containers:
                - image: "docker.io/*"
        - spec:
            template:
              spec:
                containers:
                - image: "ghcr.io/*"
        - spec:
            template:
              spec:
                containers:
                - image: "gcr.io/*"
    
    # Require image pull policy
    - name: require-image-pull-policy
      match:
        any:
        - resources:
            kinds:
              - Deployment
              - StatefulSet
              - DaemonSet
      validate:
        message: "imagePullPolicy must be set to 'Always' or 'IfNotPresent'"
        pattern:
          spec:
            template:
              spec:
                containers:
                - imagePullPolicy: "Always | IfNotPresent"
