apiVersion: batch/v1
kind: Job
metadata:
  name: freshbonds-db-init
  namespace: dev
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: db-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-init
        image: emiresh/freshbonds-user-service:v1.2.1
        workingDir: /app
        command:
          - node
          - -e
          - |
            const mongoose = require('mongoose');
            const User = require('./models/User');
            
            async function initializeDatabase() {
              const MONGODB_URI = process.env.MONGODB_URI;
              
              if (!MONGODB_URI) {
                console.error('❌ MONGODB_URI environment variable is required');
                process.exit(1);
              }
              
              try {
                console.log('🔗 Connecting to MongoDB...');
                await mongoose.connect(MONGODB_URI, {
                  maxPoolSize: 10,
                  serverSelectionTimeoutMS: 5000,
                  socketTimeoutMS: 45000,
                });
                console.log('✅ Connected to MongoDB');
                
                console.log('👤 Creating admin user...');
                const adminEmail = process.env.ADMIN_EMAIL;
                const existingUser = await User.findOne({ email: adminEmail });
                
                if (existingUser) {
                  console.log('⚠️  Admin user already exists - skipping');
                } else {
                  const adminUser = new User({
                    name: process.env.ADMIN_NAME,
                    email: adminEmail,
                    password: process.env.ADMIN_PASSWORD,
                    role: process.env.ADMIN_ROLE,
                    location: process.env.ADMIN_LOCATION,
                    farmName: process.env.ADMIN_FARMNAME,
                    mobile: process.env.ADMIN_MOBILE
                  });
                  
                  await adminUser.save();
                  console.log('✅ Admin user created successfully');
                  console.log('   Email: ' + adminEmail);
                  console.log('   Role: ' + process.env.ADMIN_ROLE);
                }
                
                const userCount = await User.countDocuments();
                console.log(`\n📋 Total users in database: ${userCount}`);
                console.log('🎉 Database initialization complete!');
                
              } catch (error) {
                console.error('❌ Initialization error:', error);
                process.exit(1);
              } finally {
                await mongoose.connection.close();
                console.log('✅ Database connection closed');
                process.exit(0);
              }
            }
            
            initializeDatabase();
        envFrom:
          - secretRef:
              name: freshbonds-secrets
          - secretRef:
              name: admin-user-init

