apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  description: Dev project
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
  sourceRepos:
    - 'https://github.com/emiresh/argo.git'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
