apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 7.0.0  # Falco 0.42.0 with kernel 6.8+ support
    chart: falco
    helm:
      values: |
        # Falco configuration - v0.42.0 with kernel 6.8+ support
        # Use modern eBPF for Oracle Cloud ARM
        driver:
          enabled: true
          kind: modern_ebpf
        
        # Enable gRPC output for falcosidekick
        grpc:
          enabled: true
          bind_address: "0.0.0.0:5060"
        
        # Enable HTTP output
        http_output:
          enabled: true
          url: "http://falcosidekick:2801"
        
        # Resource limits
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 1024Mi
        
        # Falco rules configuration
        falco:
          rules_files:
            - /etc/falco/falco_rules.yaml
            - /etc/falco/falco_rules.local.yaml
            - /etc/falco/k8s_audit_rules.yaml
            - /etc/falco/rules.d
          
          # Priority level for rules (debug, informational, notice, warning, error, critical, alert, emergency)
          priority: notice
          
          # Output configuration
          json_output: true
          json_include_output_property: true
          
          # Buffer size
          syscall_event_drops:
            actions:
              - log
              - alert
            rate: 0.03333
            max_burst: 1
        
        # Custom rules
        customRules:
          custom-rules.yaml: |-
            # Custom security rules for your cluster
            
            # Detect shell spawned in container
            - rule: Shell Spawned in Container
              desc: A shell was spawned in a container
              condition: >
                spawned_process and
                container and
                shell_procs and
                proc.tty != 0
              output: >
                Shell spawned in container (user=%user.name container=%container.name
                shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline terminal=%proc.tty
                image=%container.image.repository)
              priority: WARNING
              tags: [container, shell, mitre_execution]
            
            # Detect package management in container - simplified
            - rule: Package Management in Container
              desc: Package management tools executed in container
              condition: >
                spawned_process and
                container and
                proc.name in (apt, apt-get, yum, dnf, rpm, dpkg, apk, pip, pip3, npm, yarn)
              output: >
                Package management process in container (user=%user.name
                command=%proc.cmdline container=%container.name
                image=%container.image.repository:%container.image.tag)
              priority: WARNING
              tags: [container, process, mitre_persistence]
            
            # Detect crypto mining
            - rule: Detect Crypto Mining
              desc: Detect cryptocurrency miners
              condition: >
                spawned_process and
                (proc.name in (xmrig, cpuminer, ethminer, ccminer) or
                 proc.cmdline contains "stratum+tcp" or
                 proc.cmdline contains "xmr-stak" or
                 proc.cmdline contains "xmrig" or
                 proc.cmdline contains "minerd")
              output: >
                Crypto mining activity detected (user=%user.name
                command=%proc.cmdline container=%container.name)
              priority: CRITICAL
              tags: [process, mitre_impact]
        
        # Service account
        serviceAccount:
          create: true
          name: falco
        
        # Enable RBAC
        rbac:
          create: true
        
        # Tolerations to run on all nodes
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
        
        # Enable falcosidekick for alert routing
        falcosidekick:
          enabled: true
          replicaCount: 1
          
          # Falcosidekick configuration
          config:
            # AlertManager integration
            alertmanager:
              hostport: "http://kube-prometheus-stack-alertmanager.monitoring:9093"
              minimumpriority: "warning"
              checkcert: false
            
            # Slack integration (optional - direct from Falco)
            slack:
              webhookurl: ""  # Leave empty to use only AlertManager
              minimumpriority: "critical"
            
            # Additional outputs
            webhook:
              address: ""
            
            # Custom fields to add to alerts
            customfields: "environment:production,cluster:test-cluster"
          
          # Resources
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          
          # Web UI configuration
          webui:
            enabled: true
          
          # Service
          service:
            type: ClusterIP
            port: 2801

  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
