apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: storage
spec:
  project: default
  source:
    repoURL: https://charts.containeroo.ch
    chart: local-path-provisioner
    targetRevision: 0.0.33
    helm:
      values: |
        image:
          repository: rancher/local-path-provisioner
          tag: v0.0.33
          pullPolicy: IfNotPresent

        helperImage:
          repository: busybox
          tag: latest

        storageClass:
          create: true
          defaultClass: true
          name: local-path
          reclaimPolicy: Delete

        nodePathMap:
        - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
          paths: ["/opt/local-path-provisioner"]

        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 128Mi

        serviceAccount:
          create: true
          name: local-path-provisioner-service-account

  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
