apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.46.0
    chart: loki
    helm:
      values: |
        # Loki single binary deployment mode
        deploymentMode: SingleBinary
        
        loki:
          auth_enabled: false
          
          commonConfig:
            replication_factor: 1
          
          storage:
            type: 'filesystem'
          
          limits_config:
            retention_period: 5h
            reject_old_samples: true
            reject_old_samples_max_age: 5h
          
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
        
        singleBinary:
          replicas: 1
          
          persistence:
            enabled: true
            size: 10Gi
            storageClass: local-path
          
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 96Mi
        
        # Disable components not needed in single binary mode
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        
        # Disable memcached caches (not needed for small deployment)
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        
        # Disable memberlist (not needed for single replica)
        memberlist:
          enabled: false
        
        # Monitoring
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
        
        # Service configuration
        gateway:
          enabled: false
        
        # For log collection, use Promtail separately
        test:
          enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
