apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.app.name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
